# Generated by Django 4.2.14 on 2024-08-01 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Operations', 'Cash Flow from Operations'), ('Investing', 'Cash Flow from Investing'), ('Financing', 'Cash Flow from Financing')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cashflow.cashflowsection')),
            ],
        ),
        migrations.CreateModel(
            name='CashFlowStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_in_cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beginning_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ending_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transactions', models.ManyToManyField(related_name='statements', to='cashflow.transaction')),
            ],
        ),
    ]
